# See README for how to configure these params

log_level: info

bot:
  lang: uk
  slack_token: <SLACK_BOT_TOKEN>
  admins: bor_admin_slack_name_1,bot_admin_slack_name_2

auto_post:
  channel: general
  day: 1

karma:
  initial_value: 0
  max_shot: 5
  self_karma: Yes
  vote_timeout: 10800.0 # 3 hours
  keep_history: 7884000.0 # 3 months
  upvote_emoji:
    - "+1"
    - "partyparrot"
    - "thumbsup"
    - "thumbsup_all"
  downvote_emoji:
    - "-1"
    - "thumbsdown"

db:
  type: postgresql
  user: admin
  password: qwerty
  host: 127.0.0.1
  port: 5432
  name: mydb

# See README for how to configure these params
