[tool.poetry]
name = "karmabot"
version = "1.0.0"
description = "Slack bot that listens for and performs karma operations"
readme = "README.md"
license = "LICENSE"
authors = ["Evgen Druzhynin <evgen.druzhynin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
apscheduler = "^3.11.0"
babel = "^2.16.0"
pyyaml = "^6.0.0"
slack-sdk = "^3.33.0"
sqlalchemy = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
ruff = "^0.8.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run = "app:main"
