[tool.poetry]
name = "karmabot"
version = "1.0.0"
description = "Slack bot that listens for and performs karma operations"
readme = "README.md"
license = "LICENSE"
authors = ["Evgen Druzhynin <evgen.druzhynin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.3"
slackclient = "^2.3"
python-dateutil = "^2.8"
cryptography = "*"
pyyaml = "^5.1"
babel = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4"
flake8 = "^3.7"
pycodestyle = "2.5.0"
pydocstyle = "4.0.1"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run = "app:main"
